"""we making progress

Revision ID: ab75e241ac78
Revises: 21d23f35ef1b
Create Date: 2023-11-11 22:08:19.054299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab75e241ac78'
down_revision = '21d23f35ef1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Numeric(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
